### ISSUE TITLE
Send to Unreal - re.error: global flags not at the start of the expression at position 22

### ISSUE THREAD

**Issue by gerroon** [EpicGamesExt/BlenderTools#729]
Hi

Send to Unreal is throwing this error under Blender 4.2, Windows 11, version 2.4.3 

### In the description paste in and edit the following:
* **Addon:** Send to Unreal
* **Steps to Reproduce the Problem:** 
Add Suzanne, add a material to it, press push asset from the menu
* **Error Log:** See below
* **OS:** i.e.Windows
* **Addon Version:** i.e. Send to Unreal 1.4.0
* **Blender Version:** 4.2
* **Unreal Version:** Unreal 5.3

```
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\operators.py", line 71, in modal
    raise error
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\operators.py", line 61, in modal
    function(*args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\export.py", line 224, in export_mesh
    utilities.select_asset_collisions(asset_name, properties)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 950, in select_asset_collisions
    for mesh_object in get_asset_collisions(asset_name, properties):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 636, in get_asset_collisions
    if is_collision_of(asset_name, mesh_object.name, properties):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 832, in is_collision_of
    ) or re.fullmatch(
         ^^^^^^^^^^^^^
  File "C:\blender\4.2\python\Lib\re\__init__.py", line 171, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\4.2\python\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\4.2\python\Lib\re\_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\4.2\python\Lib\re\_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\4.2\python\Lib\re\_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\4.2\python\Lib\re\_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 22
Error: Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\operators.py", line 71, in modal
    raise error
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\operators.py", line 61, in modal
    function(*args, **kwargs)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\export.py", line 224, in export_mesh
    utilities.select_asset_collisions(asset_name, properties)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 950, in select_asset_collisions
    for mesh_object in get_asset_collisions(asset_name, properties):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 636, in get_asset_collisions
    if is_collision_of(asset_name, mesh_object.name, properties):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 832, in is_collision_of
    ) or re.fullmatch(
         ^^^^^^^^^^^^^
  File "C:\blender\4.2\python\Lib\re\__init__.py", line 171, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\4.2\python\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\4.2\python\Lib\re\_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\4.2\python\Lib\re\_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\4.2\python\Lib\re\_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender\4.2\python\Lib\re\_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 22



```

**Comment by redemprez** [comment]
I confirm this bug - also present in Blender 4.1. It would be great if it would be fixed.

**Comment by JoshQuake** [comment]
> I confirm this bug - also present in Blender 4.1. It would be great if it would be fixed. Maybe @JoshQuake could come for rescue? ;)

lol I haven't updated to 4.1 yet but might as well take a look

**Comment by PGSCOM** [comment]
> > I confirm this bug - also present in Blender 4.1. It would be great if it would be fixed. Maybe @JoshQuake could come for rescue? ;)
> 
> lol I haven't updated to 4.1 yet but might as well take a look

It also happens in 4.1, I have not updated yet and I have stayed on 4.0

**Comment by JoshQuake** [comment]
Here's a temp fix that removes (?i) regex from default lod_regex value. This makes the LOD suffix case SENSITIVE so make sure your lods match the setting 
![image](https://github.com/EpicGamesExt/BlenderTools/assets/3147154/3624acc2-0ca5-453f-a2ed-6b3ada02e7a8)

[send2ue-2.4.3_v4fixes_28-03.zip](https://github.com/EpicGamesExt/BlenderTools/files/14796450/send2ue-2.4.3_v4fixes_28-03.zip)

**Comment by redemprez** [comment]
@JoshQuake thanks very much, you are the boss. Although I still get error in Blender 4.1. Can you look at it (big please!) :)

![image](https://github.com/EpicGamesExt/BlenderTools/assets/25802640/86c28e73-43b5-4beb-84d8-d59ccad3f6c5)

**Comment by JoshQuake** [comment]
> @JoshQuake thanks very much, you are the boss. Although I still get error in Blender 4.1. Can you look at it (big please!) :)
> 
> ![image](https://private-user-images.githubusercontent.com/25802640/318009876-86c28e73-43b5-4beb-84d8-d59ccad3f6c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDQ2NDYsIm5iZiI6MTcxMTcwNDM0NiwicGF0aCI6Ii8yNTgwMjY0MC8zMTgwMDk4NzYtODZjMjhlNzMtNDNiNS00YmViLTg0ZDgtZDU5Y2NhZDNmNmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZTEzMzk4NjIxYWNjNDY5Yjg3YmJhNTljNDAyYTY4YTc0OWRiZDRjNjJkMmY4NTI3ZDJlZjM5MjRhN2Y4YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iCK3e3agaaKXQycMZtOksd37YYSbmd-Gu-nika1HWZg)

can you check your LOD settings? If yours has (?i) then remove it from there.
![image](https://github.com/EpicGamesExt/BlenderTools/assets/3147154/7c944e0b-4edc-4e4f-85bb-dc99f239fe2f)

**Comment by redemprez** [comment]
@JoshQuake - thank you, that was it! After removal plugin works correctly!

**Comment by MalikuMane** [comment]
It seems to be an issue with builds that use python 3.11. I built blender 4.0.2 with 3.11 and it also occurred there.

> > @JoshQuake thanks very much, you are the boss. Although I still get error in Blender 4.1. Can you look at it (big please!) :)
> > ![image](https://private-user-images.githubusercontent.com/25802640/318009876-86c28e73-43b5-4beb-84d8-d59ccad3f6c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDQ2NDYsIm5iZiI6MTcxMTcwNDM0NiwicGF0aCI6Ii8yNTgwMjY0MC8zMTgwMDk4NzYtODZjMjhlNzMtNDNiNS00YmViLTg0ZDgtZDU5Y2NhZDNmNmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZTEzMzk4NjIxYWNjNDY5Yjg3YmJhNTljNDAyYTY4YTc0OWRiZDRjNjJkMmY4NTI3ZDJlZjM5MjRhN2Y4YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iCK3e3agaaKXQycMZtOksd37YYSbmd-Gu-nika1HWZg)
> 
> can you check your LOD settings? If yours has (?i) then remove it from there. ![image](https://private-user-images.githubusercontent.com/3147154/318010648-7c944e0b-4edc-4e4f-85bb-dc99f239fe2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTQzNzksIm5iZiI6MTcxMjExNDA3OSwicGF0aCI6Ii8zMTQ3MTU0LzMxODAxMDY0OC03Yzk0NGUwYi00ZWRjLTRlNGYtODViYi1kYzk5ZjIzOWZlMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMDMxNDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjhiOTk3MWIxNTVhMDFiZDFjOTQ3OTc2OTcyM2IyNmQ2Mjg1ZmNkYjUwY2U1ZTg1Yzc5ZmI5ZjMyMzBhNWM1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DtnASQ5tgMrLaRqhuKm5em-0fTzIYJb0p38cJXastFM)

**Comment by Puzzabug** [comment]
Thanks for this!

**Comment by 3dcinetv** [comment]
> @JoshQuake - thank you, that was it! After removal plugin works correctly!

what did you remove? did you "uncheck" LODs?

**Comment by JoshQuake** [comment]
> > @JoshQuake - thank you, that was it! After removal plugin works correctly!
> 
> what did you remove? did you "uncheck" LODs?

Removed `(?i)` from the string

**Comment by AndrewAlexArt** [comment]
![image](https://github.com/EpicGamesExt/BlenderTools/assets/87673166/875e9962-cb59-4d16-a440-73706b892145)
Can't event install the plugin. Blender 4.1

**Comment by jdknox** [comment]
Is there a reason why the LOD regex was case-insensitive to begin with?  If so, wouldn't it be better to change the regex string to use `(?i:<pat>)` instead of just deleting the important part?

The issue is now with the _placement_ of the inline flag, not that the flag exists.

(I honestly don't know what the correct answer is, but I can offer that brute deleting flags usually isn't the best long-term approach.  No passive aggression, just speaking from my past mistakes...)

**Comment by omrkrk** [comment]
> > @JoshQuake thanks very much, you are the boss. Although I still get error in Blender 4.1. Can you look at it (big please!) :)
> > ![image](https://private-user-images.githubusercontent.com/25802640/318009876-86c28e73-43b5-4beb-84d8-d59ccad3f6c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDQ2NDYsIm5iZiI6MTcxMTcwNDM0NiwicGF0aCI6Ii8yNTgwMjY0MC8zMTgwMDk4NzYtODZjMjhlNzMtNDNiNS00YmViLTg0ZDgtZDU5Y2NhZDNmNmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZTEzMzk4NjIxYWNjNDY5Yjg3YmJhNTljNDAyYTY4YTc0OWRiZDRjNjJkMmY4NTI3ZDJlZjM5MjRhN2Y4YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iCK3e3agaaKXQycMZtOksd37YYSbmd-Gu-nika1HWZg)
> 
> can you check your LOD settings? If yours has (?i) then remove it from there. ![image](https://private-user-images.githubusercontent.com/3147154/318010648-7c944e0b-4edc-4e4f-85bb-dc99f239fe2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTMyMzAsIm5iZiI6MTcyMTMxMjkzMCwicGF0aCI6Ii8zMTQ3MTU0LzMxODAxMDY0OC03Yzk0NGUwYi00ZWRjLTRlNGYtODViYi1kYzk5ZjIzOWZlMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MThUMTQyODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ2OGQ5OTQwZDc0YTFkOTRhNzAyMjE1ZmE1NTlhMTBjMjQwMDdiNjA4NzU2MzA3MjQ5MjgzNzg4NTJjOWY3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.C_NZ7IrXcOpe1x8p5cMbc-pvq2O91riYolZ86ZSE2mw)

@JoshQuake 
I cant find this tab. how can I reach this tab

**Comment by larieflor** [comment]
> > > @JoshQuake thanks very much, you are the boss. Although I still get error in Blender 4.1. Can you look at it (big please!) :)
> > > ![image](https://private-user-images.githubusercontent.com/25802640/318009876-86c28e73-43b5-4beb-84d8-d59ccad3f6c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDQ2NDYsIm5iZiI6MTcxMTcwNDM0NiwicGF0aCI6Ii8yNTgwMjY0MC8zMTgwMDk4NzYtODZjMjhlNzMtNDNiNS00YmViLTg0ZDgtZDU5Y2NhZDNmNmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZTEzMzk4NjIxYWNjNDY5Yjg3YmJhNTljNDAyYTY4YTc0OWRiZDRjNjJkMmY4NTI3ZDJlZjM5MjRhN2Y4YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iCK3e3agaaKXQycMZtOksd37YYSbmd-Gu-nika1HWZg)
> > 
> > 
> > can you check your LOD settings? If yours has (?i) then remove it from there. ![image](https://private-user-images.githubusercontent.com/3147154/318010648-7c944e0b-4edc-4e4f-85bb-dc99f239fe2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTMyMzAsIm5iZiI6MTcyMTMxMjkzMCwicGF0aCI6Ii8zMTQ3MTU0LzMxODAxMDY0OC03Yzk0NGUwYi00ZWRjLTRlNGYtODViYi1kYzk5ZjIzOWZlMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MThUMTQyODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ2OGQ5OTQwZDc0YTFkOTRhNzAyMjE1ZmE1NTlhMTBjMjQwMDdiNjA4NzU2MzA3MjQ5MjgzNzg4NTJjOWY3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.C_NZ7IrXcOpe1x8p5cMbc-pvq2O91riYolZ86ZSE2mw)
> 
> @JoshQuake I cant find this tab. how can I reach this tab

Go to Pipeline tab > Export > Settings Dialog > Click Import tab and under LOD Settings

**Comment by omrkrk** [comment]
@larieflor ty  but that wasn't the solution to my problem. can you help me about it.

`Python: Traceback (most recent call last):
  File "C:\Users\yasar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\operators.py", line 71, in modal
    raise error
  File "C:\Users\yasar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\operators.py", line 61, in modal
    function(*args, **kwargs)
  File "C:\Users\yasar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\export.py", line 224, in export_mesh
    utilities.select_asset_collisions(asset_name, properties)
  File "C:\Users\yasar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 950, in select_asset_collisions
    for mesh_object in get_asset_collisions(asset_name, properties):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yasar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 636, in get_asset_collisions
    if is_collision_of(asset_name, mesh_object.name, properties):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yasar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 832, in is_collision_of
    ) or re.fullmatch(
         ^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\re\__init__.py", line 171, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\re\_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\re\_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\re\_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\re\_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 24
`

**Comment by larieflor** [comment]
> @larieflor ty  but that wasn't the solution to my problem. can you help me about it.
> 
> `Python: Traceback (most recent call last):
>   File "C:\Users\yasar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\operators.py", line 71, in modal
>     raise error
>   File "C:\Users\yasar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\operators.py", line 61, in modal
>     function(*args, **kwargs)
>   File "C:\Users\yasar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\export.py", line 224, in export_mesh
>     utilities.select_asset_collisions(asset_name, properties)
>   File "C:\Users\yasar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 950, in select_asset_collisions
>     for mesh_object in get_asset_collisions(asset_name, properties):
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\yasar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 636, in get_asset_collisions
>     if is_collision_of(asset_name, mesh_object.name, properties):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\yasar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\send2ue\core\utilities.py", line 832, in is_collision_of
>     ) or re.fullmatch(
>          ^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\re\__init__.py", line 171, in fullmatch
>     return _compile(pattern, flags).fullmatch(string)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\re\__init__.py", line 294, in _compile
>     p = _compiler.compile(pattern, flags)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\re\_compiler.py", line 745, in compile
>     p = _parser.parse(p, flags)
>         ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\re\_parser.py", line 989, in parse
>     p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\re\_parser.py", line 464, in _parse_sub
>     itemsappend(_parse(source, state, verbose, nested + 1,
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\re\_parser.py", line 850, in _parse
>     raise source.error('global flags not at the start '
> re.error: global flags not at the start of the expression at position 24
> `

try going to Blender preferences, under Add ons and down to Preferences, change the RPC Response timeout to 99999

**Comment by jack-yao91** [comment]
The error is a Regex error. It is related changes in `re` module in python 3.11. We fixed it in the `2.4.5` version of the addon in our fork.

**Comment by larieflor** [comment]
> The error is a Regex error. It is related to changes in `re` module in python 3.11. We fixed it in the `2.4.5` version of the addon in our fork.

I see, thank you so much! 2.4.5 worked smoothly on my end now.

**Comment by xxxx626** [comment]
> @JoshQuake I cant find this tab. how can I reach this tab

It's in you blender: pipline->export->setting Dialog
