### ISSUE TITLE
Send2UE Broken export on Blender 4.1

### ISSUE THREAD

**Issue by Hopefullyidontgetbanned** [EpicGamesExt/BlenderTools#735]
Send to Unreal
Pipeline > Export > Send to Unreal
* **Error Log:** ` Python: Traceback (most recent call last):
  File "C:\Users\Hope\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\operators.py", line 71, in modal
    raise error
  File "C:\Users\Hope\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\operators.py", line 61, in modal
    function(*args, **kwargs)
  File "C:\Users\Hope\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\export.py", line 224, in export_mesh
    utilities.select_asset_collisions(asset_name, properties)
  File "C:\Users\Hope\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\utilities.py", line 950, in select_asset_collisions
    for mesh_object in get_asset_collisions(asset_name, properties):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hope\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\utilities.py", line 636, in get_asset_collisions
    if is_collision_of(asset_name, mesh_object.name, properties):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hope\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\send2ue\core\utilities.py", line 832, in is_collision_of
    ) or re.fullmatch(
         ^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\re\__init__.py", line 171, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\re\_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\re\_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\re\_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\re\_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 27`
* **OS.** Windows 11
* **Add-on Version.** Send to Unreal 2.43
* **Blender Version:** Blender 4.1.0
* **Unreal Version:** Unreal 5.3

**Comment by Hopefullyidontgetbanned** [comment]
Can confirm it works, but won't close the issue  since no fixes has been pushed to the main branch

**Comment by NeptunoBM** [comment]
Same error here.

**Comment by AndrewAlexArt** [comment]
How did this error end up in the main branch?..

**Comment by jack-yao91** [comment]
Epic hasn't made any updates to this since blender 3.6 and looks like probably wont maintain the project anymore, so we created a fork here:
https://github.com/poly-hammer/BlenderTools

This new [release](https://github.com/poly-hammer/BlenderTools/releases/tag/20240612211049) supports blender 4.1.
