### ISSUE TITLE
UE to Rigify -  Not Working, UE2Rigify 1.6.2, Blender 4.2

### ISSUE THREAD

**Issue by tommywright** [EpicGamesExt/BlenderTools#755]
Send to Unreal does nothing on Convert
Import Mannequin FBX (Standard UE4 Mannequin tested)
Windows 11
UE to Rigify v1.6.2
Blender v4.2

* **Error Log:** Paste the full error log.....

Traceback (most recent call last):
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\ue2rigify\core\scene.py", line 1649, in switch_modes
    convert_to_control_rig(properties)
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\ue2rigify\core\scene.py", line 1563, in convert_to_control_rig
    control_rig_object = create_control_rig(properties)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\ue2rigify\core\scene.py", line 779, in create_control_rig
    create_meta_rig(properties)
  File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\ue2rigify\core\scene.py", line 756, in create_meta_rig
    metarig.create(metarig_object)
  File "C:\Users\tvtom\AppData\Local\Temp\ue2rigify\resources\rig_templates\male_mannequin\metarig.py", line 47, in create
    arm.rigify_layers.add()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'Armature' object has no attribute 'rigify_layers'. Did you mean: 'rigify_colors'?
File "C:\Users\tvtom\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\ue2rigify\core\scene.py", line 1602, in switch_modes

**Comment by jack-yao91** [comment]
Check out this fork. (The Epic repo is no longer maintained)
https://github.com/poly-hammer/BlenderTools

**Comment by tommywright** [comment]
Thanks for the info!!
